# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTesterror():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testerror(self):
    # Test name: testerror
    # Step # | name | target | value
    # 1 | open | /app/ | 
    self.driver.get("https://platformrc.wyscout.com/app/")
    # 2 | setWindowSize | 1280x708 | 
    self.driver.set_window_size(1280, 708)
    # 3 | click | css=h3 | 
    self.driver.find_element(By.CSS_SELECTOR, "h3").click()
    # 4 | click | linkText=Logout | 
    self.driver.find_element(By.LINK_TEXT, "Logout").click()
    # 5 | click | id=login_username | 
    self.driver.find_element(By.ID, "login_username").click()
    # 6 | type | id=login_username | ruchabhosale96@gmai.com
    self.driver.find_element(By.ID, "login_username").send_keys("ruchabhosale96@gmai.com")
    # 7 | click | id=login_password | 
    self.driver.find_element(By.ID, "login_password").click()
    # 8 | type | id=login_password | rucha123
    self.driver.find_element(By.ID, "login_password").send_keys("rucha123")
    # 9 | click | id=login_button | 
    self.driver.find_element(By.ID, "login_button").click()
    # 10 | click | css=#AfaQog3zqPSCtU4TKMDSrJMetoTICRB4_button .icon-pre | 
    self.driver.find_element(By.CSS_SELECTOR, "#AfaQog3zqPSCtU4TKMDSrJMetoTICRB4_button .icon-pre").click()
  
